# Generated by Django 4.2.4 on 2023-08-30 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_category_language_delete_image_category_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Опыт',
                'verbose_name_plural': 'Опыт',
            },
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image')),
                ('description', models.TextField(max_length=500, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Principle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Принцип',
                'verbose_name_plural': 'Принципы',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image')),
            ],
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Язык', 'verbose_name_plural': 'Языки'},
        ),
        migrations.AlterField(
            model_name='language',
            name='title',
            field=models.CharField(max_length=20, verbose_name='title'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='products',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.language'),
        ),
        migrations.AddField(
            model_name='principle',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.language'),
        ),
        migrations.AddField(
            model_name='practice',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.language'),
        ),
        migrations.AddField(
            model_name='experience',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.language'),
        ),
    ]
