# Generated by Django 4.2.4 on 2023-08-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_products_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='principle',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='principle',
            name='title_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='principle',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='products',
            name='description_en',
            field=models.TextField(max_length=100, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='products',
            name='description_ky',
            field=models.TextField(max_length=100, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='products',
            name='description_ru',
            field=models.TextField(max_length=100, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='products',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='products',
            name='title_ky',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='products',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
    ]
