# Generated by Django 4.2.4 on 2023-08-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_principle_title_en_principle_title_ky_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='description_en',
            field=models.TextField(max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='description_ky',
            field=models.TextField(max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='description_ru',
            field=models.TextField(max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='title_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
    ]
