# Generated by Django 4.2.4 on 2023-09-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_photo_options_alter_video_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(max_length=120, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title_en',
            field=models.CharField(max_length=120, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title_ky',
            field=models.CharField(max_length=120, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title_ru',
            field=models.CharField(max_length=120, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=25, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='products',
            name='title_en',
            field=models.CharField(max_length=25, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='products',
            name='title_ky',
            field=models.CharField(max_length=25, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='products',
            name='title_ru',
            field=models.CharField(max_length=25, null=True, verbose_name='title'),
        ),
    ]
