# Generated by Django 4.2.4 on 2023-09-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_experience_title_en_experience_title_ky_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, verbose_name='phone')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('address_en', models.CharField(max_length=100, null=True, verbose_name='address')),
                ('address_ru', models.CharField(max_length=100, null=True, verbose_name='address')),
                ('address_ky', models.CharField(max_length=100, null=True, verbose_name='address')),
            ],
        ),
    ]
